src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $firstname = null;

    #[ORM\Column(length: 255)]
    private ?string $lastname = null;

    /**
     * @var Collection<int, VeterinaryReport>
     */
    #[ORM\OneToMany(targetEntity: VeterinaryReport::class, mappedBy: 'veterinary')]
    private Collection $vetReport;

    /**
     * @var Collection<int, FoodConsumption>
     */
    #[ORM\OneToMany(targetEntity: FoodConsumption::class, mappedBy: 'employee')]
    private Collection $foodCons;

    public function __construct()
    {
        $this->vetReport = new ArrayCollection();
        $this->foodCons = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): static
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): static
    {
        $this->lastname = $lastname;

        return $this;
    }

    /**
     * @return Collection<int, VeterinaryReport>
     */
    public function getVetReport(): Collection
    {
        return $this->vetReport;
    }

    public function addVetReport(VeterinaryReport $vetReport): static
    {
        if (!$this->vetReport->contains($vetReport)) {
            $this->vetReport->add($vetReport);
            $vetReport->setVeterinary($this);
        }

        return $this;
    }

    public function removeVetReport(VeterinaryReport $vetReport): static
    {
        if ($this->vetReport->removeElement($vetReport)) {
            // set the owning side to null (unless already changed)
            if ($vetReport->getVeterinary() === $this) {
                $vetReport->setVeterinary(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, FoodConsumption>
     */
    public function getFoodCons(): Collection
    {
        return $this->foodCons;
    }

    public function addFoodCon(FoodConsumption $foodCon): static
    {
        if (!$this->foodCons->contains($foodCon)) {
            $this->foodCons->add($foodCon);
            $foodCon->setEmployee($this);
        }

        return $this;
    }

    public function removeFoodCon(FoodConsumption $foodCon): static
    {
        if ($this->foodCons->removeElement($foodCon)) {
            // set the owning side to null (unless already changed)
            if ($foodCon->getEmployee() === $this) {
                $foodCon->setEmployee(null);
            }
        }

        return $this;
    }

    public function getFormattedRoles(): string
    {
        return implode(', ', $this->getRoles());
    }

    public function __toString(): string
    {
        return $this->getFirstname().' '.$this->getLastname();
    }
}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class SecurityController extends AbstractController
{
    #[Route(path: '/login', name: 'app_login')]
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        $page_name = 'login';
        if ($this->getUser()) {
            return $this->redirectToRoute('app_profile_show', ['profileNumber' => 'EMP-'.(new \ReflectionClass($this->getUser()))->getMethod('getId')->invoke($this->getUser())]);
        }

        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', ['last_username' => $lastUsername, 'error' => $error, 'page_name' => $page_name]);
    }

    #[Route(path: '/logout', name: 'app_logout')]
    public function logout(): void
    {
        $page_name = 'logout';
        throw new \LogicException('This method can be blank - it will be intercepted by the logout key on your firewall.');
    }
}

templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}Log in!{% endblock %}

{% block body %}
<section class="flex">
    <form method="post" class="flex flex-col items-center h-screen w-full pt-5 pb-64 px-8 md:pt-20">
        <img class="w-64 max-w-xl drop-shadow-sm mb-10 sm:w-80 md:w-96" src="images/logo/zoo-logo_transparentBG_bloc_dark.svg" alt="Logo without Background">
        {% if error %}
            <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
        {% endif %}

        {% if app.user %}
            <div class="mb-3">
                You are logged in as {{ app.user.userIdentifier }},
            </div>
            <a href="{{ path('app_logout') }}">
                Logout
            </a>
        {% else %}
            <h1 class="mb-3 font-header text-3xl text-center tracking-tight capitalize text-secBrown tracking-tight md:text-5xl md:leading-[52px]">Please sign in !</h1>
            <div class="flex flex-col w-full max-w-[792px] gap-5">
                <div class="flex flex-col w-full">
                    <label for="inputEmail" class="block pb-2 text-[#1F5906] text-sm italic tracking-wider">Email</label>
                    <input type="email" value="{{ last_username }}" name="email" id="inputEmail" class="form-control block text-base tracking-wider w-full p-2 border-[0.5px] border-[#1F5906] bg-[#1F5906]/[.02] rounded placeholder:text-[#B3ADA9] placeholder:text-base invalid:border-[#D43E35] invalid:text-[#D43E35] focus:border-[#2A66DB] focus:ring-1 focus:outline-none focus:ring-[#2A66DB]" autocomplete="email" required autofocus>
                </div>
                <div class="flex flex-col w-full">
                    <label for="inputPassword" class="block pb-2 text-[#1F5906] text-sm italic tracking-wider">Password</label>
                    <input type="password" name="password" id="inputPassword" class="form-control form-control block text-base tracking-wider w-full p-2 border-[0.5px] border-[#1F5906] bg-[#1F5906]/[.02] rounded placeholder:text-[#B3ADA9] placeholder:text-base invalid:border-[#D43E35] invalid:text-[#D43E35] focus:border-[#2A66DB] focus:ring-1 focus:outline-none focus:ring-[#2A66DB]" autocomplete="current-password" required>
                </div>

                <input type="hidden" name="_csrf_token"
                    value="{{ csrf_token('authenticate') }}"
                >
                
                <div class="self-center">
                    {{ component('Button', {text: 'Connexion', size:'medium', isPrimary: true, isCta: true, isSubmit: true, labelColor: ''}) }}
                </div>
            </div>
        {% endif %}
    </form>
</section>


{% endblock %}